//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricRecord
    {
        public int Id { get; set; }
        public double Measurement { get; set; }
        public int MetricTypeId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int UserId { get; set; }
    
        public virtual MetricType MetricType { get; set; }
        public virtual webpages_Users webpages_Users { get; set; }
    }
}
