//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetricType()
        {
            this.MetricRecords = new HashSet<MetricRecord>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public int MetricUnitId { get; set; }
        public int MetricClassId { get; set; }
    
        public virtual MetricClass MetricClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetricRecord> MetricRecords { get; set; }
        public virtual MetricUnit MetricUnit { get; set; }
    }
}
