//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutExerciseLinkCompleted
    {
        public int Id { get; set; }
        public int WorkoutExerciseLinkId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Sets { get; set; }
        public int Repititions { get; set; }
        public System.TimeSpan Duration { get; set; }
        public double Weight { get; set; }
    
        public virtual WorkoutExercisesLInk WorkoutExercisesLInk { get; set; }
    }
}
