//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutExercis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkoutExercis()
        {
            this.WorkoutExercisesLInks = new HashSet<WorkoutExercisesLInk>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Exercise { get; set; }
        public string Instructions { get; set; }
    
        public virtual WorkoutExerciseCategory WorkoutExerciseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutExercisesLInk> WorkoutExercisesLInks { get; set; }
    }
}
