//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkoutUser()
        {
            this.WorkoutExercisesLInks = new HashSet<WorkoutExercisesLInk>();
        }
    
        public int Id { get; set; }
        public string Workout { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int UserId { get; set; }
        public System.TimeSpan Duration { get; set; }
    
        public virtual webpages_Users webpages_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutExercisesLInk> WorkoutExercisesLInks { get; set; }
    }
}
